#
# the developer_id the telegram user id where the errors should be sent.
#

token = "<telegram-token>"
developer_id = "<telegram-developer_id>"
qrz_call = "<call>"
qrz_key = "<qrz-api-ley>"
dbname = "<home>/.local/qrzbot.sqlite"
